### PR TITLE
Find workspace root

### LINKED ISSUE #238: Codeium Chat doesn't work in Neovim
I encounter this problem when running `:Codeium Chat`. It throws these errors
```
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:300: post http://127.0.0.1:38731/exa.language_server_pb.LanguageServerService/AddTrackedWorkspace - curl error exit_code=52 stderr={ "curl: (52) Empty reply from server" }
stack traceback:
	[C]: in function 'error'
	....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:300: in function '_user_on_exit'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:241: in function '_shutdown'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:48: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:39>
```

I run `:che codeium` and here is what I get 
```
Codeium: checking Codeium server status ~
- OK API key properly loaded
- Checking server status
- OK Server is healthy on port: 38731
- Language Server binary: /home/brianhuster/.cache/nvim/codeium/bin/1.20.6/language_server_linux_x64
- Last heartbeat: 10/04/24 23:51:59
- OK Heartbeat ok
```

So basically health check says server is healthy on port 38731, but plenary.nvim says that server sent empty reply.

### LINKED ISSUE #244: get_relative_path is not returning actual relative path
https://github.com/Exafunction/codeium.nvim/blob/ed65f0a5262c746b2d69a7ae67af7c1da89f94ab/lua/codeium/util.lua#L39

`:` is not a valid argument here. I think it should perhaps be `:.`. Currently it just sends the absolute path instead due to the invalid specifier.

I'm not sure of the impact of making this change though so I'm not submitting a PR just yet. I imagine that any changes here that feed into a `workspace_uri` parameter would have to be careful to be relative to the actual workspace root indicated to the LSP, and not just the CWD, although for the moment those are the same in this plugin (`codeium.vim` works a bit differently in that respect).

### PR DESCRIPTION
**Pull request by dimfeld**
This provides a few methods of finding the workspace root (see comment below) and updates the calls that use `workspace_uri` to use it.

Closes #244 
Closes #238 
Supersedes #243

### CODE REVIEW

File: lua/codeium/util.lua [hunk 1]
```diff
@@ -35,8 +37,39 @@ function M.get_newline(bufnr)
...
+local cached_roots = {}
+function M.get_project_root()
+	local cwd = vim.fn.getcwd()
+
+	if cached_roots[cwd] then
+		return cached_roots[cwd]
+	end
+
+	-- From the CWD, walk up the tree looking for a directory that contains one of the project root files
+	local candidates = config.options.project_root_paths
```
Comment (pqn) [inline lua/codeium/util.lua:56]: Maybe the source of candidates should be `vim.lsp.buf.list_workspace_folders()`?

**Review by pqn — COMMENTED** [review]
Thanks for this PR, definitely the existing relative path wasn't computed correctly. The `workspace_uri` argument is expected to be `file:///path/to/workspace` (convention changed from relative path to the other path components basically) just like the`absolute_uri` argument is expected to be `file:///path/to/workspace/foo/bar.txt`.

File: lua/codeium/util.lua (hunk 1 above)
Comment (dimfeld) [reply lua/codeium/util.lua:56]: That seems like a good idea. Personally I'm actually still on coc.nvim so I'll probably keep the project_root_paths option as a fallback when `list_workspace_folders` returns nothing.

Comment (pqn) [reply lua/codeium/util.lua:56]: Sounds reasonable.

**Comment by dimfeld** [comment]
Ok I think this is looking good now. I implemented a 4-step process:

1. If provided, call an optional function to find the workspace root which can be provided to `setup`. I'm using this to ask coc.nvim for the workspace root in my config.
2. Query the LSP support for the workspace folders
3. Search upwards in the filesystem
4. Use the CWD

**Review by saranshsaini — APPROVED** [review]

File: lua/codeium/util.lua [hunk 2]
```diff
@@ -35,8 +36,50 @@ function M.get_newline(bufnr)
...
+		root = vim.lsp.buf.list_workspace_folders()[0]
+		if root then
+			return root
+		end
+	end
+
+	-- From the CWD, walk up the tree looking for a directory that contains one of the project root files
+	local candidates = config.options.workspace_root.paths
+	local result = vim.fs.find(candidates, {
+		path = cwd,
```
Comment (saranshsaini) [inline lua/codeium/util.lua:58]: @dimfeld where is this cwd variable coming from? I notice that this pr fixed things for mac, but on windows it fails. Seems the failure is because this cwd variable is nil. How does it get populated on mac?

Comment (dimfeld) [reply lua/codeium/util.lua:58]: Ah sorry, that was missed when I was moving around some code. `M.get_project_root` should pass its `wd` variable to `_get_project_root` for the value of `cwd`.

Comment (dimfeld) [reply lua/codeium/util.lua:58]: Submitted #248 as a fix
